# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mq_pb2 as mq__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RocketMQGatewayStub(object):
    """====================================================================
    核心服务定义：RocketMQGateway (Simple)
    ====================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/mq.RocketMQGateway/SendMessage',
                request_serializer=mq__pb2.SendRequest.SerializeToString,
                response_deserializer=mq__pb2.SendResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/mq.RocketMQGateway/Subscribe',
                request_serializer=mq__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=mq__pb2.MessageResponse.FromString,
                _registered_method=True)


class RocketMQGatewayServicer(object):
    """====================================================================
    核心服务定义：RocketMQGateway (Simple)
    ====================================================================
    """

    def SendMessage(self, request, context):
        """1. 发送消息：同步发送
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """2. 消费消息：客户端发起订阅，服务端持续推送消息流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RocketMQGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=mq__pb2.SendRequest.FromString,
                    response_serializer=mq__pb2.SendResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=mq__pb2.SubscribeRequest.FromString,
                    response_serializer=mq__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mq.RocketMQGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mq.RocketMQGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RocketMQGateway(object):
    """====================================================================
    核心服务定义：RocketMQGateway (Simple)
    ====================================================================
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mq.RocketMQGateway/SendMessage',
            mq__pb2.SendRequest.SerializeToString,
            mq__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mq.RocketMQGateway/Subscribe',
            mq__pb2.SubscribeRequest.SerializeToString,
            mq__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
