# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08mq.proto\x12\x02mq\"F\n\x0bSendRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\x11\n\x04tags\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_tags\"L\n\x0cSendResponse\x12\r\n\x05msgId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"T\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x15\n\rconsumerGroup\x18\x02 \x01(\t\x12\x11\n\x04tags\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_tags\"=\n\x0fMessageResponse\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\r\n\x05msgId\x18\x03 \x01(\t2}\n\x0fRocketMQGateway\x12\x30\n\x0bSendMessage\x12\x0f.mq.SendRequest\x1a\x10.mq.SendResponse\x12\x38\n\tSubscribe\x12\x14.mq.SubscribeRequest\x1a\x13.mq.MessageResponse0\x01\x42\x11Z\x0f./proto;mqprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./proto;mqproto'
  _globals['_SENDREQUEST']._serialized_start=16
  _globals['_SENDREQUEST']._serialized_end=86
  _globals['_SENDRESPONSE']._serialized_start=88
  _globals['_SENDRESPONSE']._serialized_end=164
  _globals['_SUBSCRIBEREQUEST']._serialized_start=166
  _globals['_SUBSCRIBEREQUEST']._serialized_end=250
  _globals['_MESSAGERESPONSE']._serialized_start=252
  _globals['_MESSAGERESPONSE']._serialized_end=313
  _globals['_ROCKETMQGATEWAY']._serialized_start=315
  _globals['_ROCKETMQGATEWAY']._serialized_end=440
# @@protoc_insertion_point(module_scope)
