// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: proto/mq.proto

package mqproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====================================================================
// 消息发送 (Producer) 结构
// ====================================================================
type SendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Topic string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// 消息内容，使用 bytes 类型更通用
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// 可选：消息标签，用于消费者过滤
	Tags          *string `protobuf:"bytes,3,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_proto_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendRequest) GetTags() string {
	if x != nil && x.Tags != nil {
		return *x.Tags
	}
	return ""
}

type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RocketMQ 返回的消息 ID
	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// 简单的成功或失败状态
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 如果失败，返回错误信息
	Error         *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ====================================================================
// 消息订阅/消费 (Consumer) 结构
// ====================================================================
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Topic string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// 对应 RocketMQ 的 Consumer Group Name，这是必须的
	ConsumerGroup string `protobuf:"bytes,2,opt,name=consumerGroup,proto3" json:"consumerGroup,omitempty"`
	// 新增：用于按标签过滤消息。多个标签可以用双竖线 || 分隔
	Tags          *string `protobuf:"bytes,3,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *SubscribeRequest) GetTags() string {
	if x != nil && x.Tags != nil {
		return *x.Tags
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_proto_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{3}
}

func (x *MessageResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MessageResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MessageResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

var File_proto_mq_proto protoreflect.FileDescriptor

const file_proto_mq_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/mq.proto\x12\x02mq\"Y\n" +
	"\vSendRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x17\n" +
	"\x04tags\x18\x03 \x01(\tH\x00R\x04tags\x88\x01\x01B\a\n" +
	"\x05_tags\"c\n" +
	"\fSendResponse\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"p\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12$\n" +
	"\rconsumerGroup\x18\x02 \x01(\tR\rconsumerGroup\x12\x17\n" +
	"\x04tags\x18\x03 \x01(\tH\x00R\x04tags\x88\x01\x01B\a\n" +
	"\x05_tags\"Q\n" +
	"\x0fMessageResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\tR\x05msgId2}\n" +
	"\x0fRocketMQGateway\x120\n" +
	"\vSendMessage\x12\x0f.mq.SendRequest\x1a\x10.mq.SendResponse\x128\n" +
	"\tSubscribe\x12\x14.mq.SubscribeRequest\x1a\x13.mq.MessageResponse0\x01B\x11Z\x0f./proto;mqprotob\x06proto3"

var (
	file_proto_mq_proto_rawDescOnce sync.Once
	file_proto_mq_proto_rawDescData []byte
)

func file_proto_mq_proto_rawDescGZIP() []byte {
	file_proto_mq_proto_rawDescOnce.Do(func() {
		file_proto_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)))
	})
	return file_proto_mq_proto_rawDescData
}

var file_proto_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_mq_proto_goTypes = []any{
	(*SendRequest)(nil),      // 0: mq.SendRequest
	(*SendResponse)(nil),     // 1: mq.SendResponse
	(*SubscribeRequest)(nil), // 2: mq.SubscribeRequest
	(*MessageResponse)(nil),  // 3: mq.MessageResponse
}
var file_proto_mq_proto_depIdxs = []int32{
	0, // 0: mq.RocketMQGateway.SendMessage:input_type -> mq.SendRequest
	2, // 1: mq.RocketMQGateway.Subscribe:input_type -> mq.SubscribeRequest
	1, // 2: mq.RocketMQGateway.SendMessage:output_type -> mq.SendResponse
	3, // 3: mq.RocketMQGateway.Subscribe:output_type -> mq.MessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mq_proto_init() }
func file_proto_mq_proto_init() {
	if File_proto_mq_proto != nil {
		return
	}
	file_proto_mq_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_mq_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_mq_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mq_proto_goTypes,
		DependencyIndexes: file_proto_mq_proto_depIdxs,
		MessageInfos:      file_proto_mq_proto_msgTypes,
	}.Build()
	File_proto_mq_proto = out.File
	file_proto_mq_proto_goTypes = nil
	file_proto_mq_proto_depIdxs = nil
}
